#!/usr/bin/env bash
# Safety net: ensure .env exists even after eb setenv (which skips predeploy hooks)
# This runs after every deployment, including config-only updates

set -e

APP_DIR="/var/app/current"
ENV_FILE="$APP_DIR/.env"

generate_env() {
 cat > "$ENV_FILE" <<EOF
APP_NAME=ProcuChain
APP_ENV=${APP_ENV:-production}
APP_KEY=${APP_KEY:-}
APP_DEBUG=${APP_DEBUG:-false}
APP_URL=http://procuchain-prod.eba-vujm352s.us-east-1.elasticbeanstalk.com

LOG_CHANNEL=stderr

DB_CONNECTION=mysql
DB_HOST=${DB_HOST:-127.0.0.1}
DB_PORT=3306
DB_DATABASE=${DB_DATABASE:-procuchain}
DB_USERNAME=${DB_USERNAME:-procuchain}
DB_PASSWORD=${DB_PASSWORD:-}

MULTICHAIN_CHAIN_NAME=${MULTICHAIN_CHAIN_NAME:-procuchain}
MULTICHAIN_RPC_HOST=${MULTICHAIN_RPC_HOST:-127.0.0.1}
MULTICHAIN_RPC_PORT=${MULTICHAIN_RPC_PORT:-6834}
MULTICHAIN_RPC_USERNAME=${MULTICHAIN_RPC_USERNAME:-multichainrpc}
MULTICHAIN_RPC_PASSWORD=${MULTICHAIN_RPC_PASSWORD:-multichainrpc}
MULTICHAIN_MASTER_PORT=${MULTICHAIN_MASTER_PORT:-6835}
MULTICHAIN_USE_SSL=${MULTICHAIN_USE_SSL:-false}
MULTICHAIN_VERIFY_SSL=${MULTICHAIN_VERIFY_SSL:-false}
MULTICHAIN_CONNECTION_TIMEOUT=${MULTICHAIN_CONNECTION_TIMEOUT:-30}
MULTICHAIN_MAX_RETRIES=${MULTICHAIN_MAX_RETRIES:-3}

MULTICHAIN_NODE_ADMIN_IP=${MULTICHAIN_NODE_ADMIN_IP:-127.0.0.1}
MULTICHAIN_NODE_ADMIN_PRIVATE_IP=${MULTICHAIN_NODE_ADMIN_PRIVATE_IP:-127.0.0.1}
MULTICHAIN_NODE_ADMIN_RPC_PORT=${MULTICHAIN_NODE_ADMIN_RPC_PORT:-6834}
MULTICHAIN_NODE_ADMIN_P2P_PORT=${MULTICHAIN_NODE_ADMIN_P2P_PORT:-6835}
MULTICHAIN_NODE_ADMIN_NAME=${MULTICHAIN_NODE_ADMIN_NAME:-Primary Node}
MULTICHAIN_NODE_ADMIN_ROLE=${MULTICHAIN_NODE_ADMIN_ROLE:-Administrator}

MULTICHAIN_NODE_BAC_SECRETARIAT_IP=${MULTICHAIN_NODE_BAC_SECRETARIAT_IP:-127.0.0.1}
MULTICHAIN_NODE_BAC_SECRETARIAT_PRIVATE_IP=${MULTICHAIN_NODE_BAC_SECRETARIAT_PRIVATE_IP:-127.0.0.1}
MULTICHAIN_NODE_BAC_SECRETARIAT_RPC_PORT=${MULTICHAIN_NODE_BAC_SECRETARIAT_RPC_PORT:-6834}
MULTICHAIN_NODE_BAC_SECRETARIAT_P2P_PORT=${MULTICHAIN_NODE_BAC_SECRETARIAT_P2P_PORT:-6835}
MULTICHAIN_NODE_BAC_SECRETARIAT_NAME=${MULTICHAIN_NODE_BAC_SECRETARIAT_NAME:-BAC Secretariat}
MULTICHAIN_NODE_BAC_SECRETARIAT_ROLE=${MULTICHAIN_NODE_BAC_SECRETARIAT_ROLE:-Secretariat}

MULTICHAIN_NODE_BAC_CHAIRMAN_IP=${MULTICHAIN_NODE_BAC_CHAIRMAN_IP:-127.0.0.1}
MULTICHAIN_NODE_BAC_CHAIRMAN_PRIVATE_IP=${MULTICHAIN_NODE_BAC_CHAIRMAN_PRIVATE_IP:-127.0.0.1}
MULTICHAIN_NODE_BAC_CHAIRMAN_RPC_PORT=${MULTICHAIN_NODE_BAC_CHAIRMAN_RPC_PORT:-6834}
MULTICHAIN_NODE_BAC_CHAIRMAN_P2P_PORT=${MULTICHAIN_NODE_BAC_CHAIRMAN_P2P_PORT:-6835}
MULTICHAIN_NODE_BAC_CHAIRMAN_NAME=${MULTICHAIN_NODE_BAC_CHAIRMAN_NAME:-BAC Chairman}
MULTICHAIN_NODE_BAC_CHAIRMAN_ROLE=${MULTICHAIN_NODE_BAC_CHAIRMAN_ROLE:-Chairman}

MULTICHAIN_NODE_HOPE_IP=${MULTICHAIN_NODE_HOPE_IP:-127.0.0.1}
MULTICHAIN_NODE_HOPE_PRIVATE_IP=${MULTICHAIN_NODE_HOPE_PRIVATE_IP:-127.0.0.1}
MULTICHAIN_NODE_HOPE_RPC_PORT=${MULTICHAIN_NODE_HOPE_RPC_PORT:-6834}
MULTICHAIN_NODE_HOPE_P2P_PORT=${MULTICHAIN_NODE_HOPE_P2P_PORT:-6835}
MULTICHAIN_NODE_HOPE_NAME=${MULTICHAIN_NODE_HOPE_NAME:-HOPE}
MULTICHAIN_NODE_HOPE_ROLE=${MULTICHAIN_NODE_HOPE_ROLE:-HOPE}
EOF
 chown webapp:webapp "$ENV_FILE"
}

if [ ! -f "$ENV_FILE" ]; then
 echo "POSTDEPLOY: .env missing — regenerating from environment variables"
 generate_env
 echo "POSTDEPLOY: .env generated successfully"
else
 echo "POSTDEPLOY: .env already exists — checking for missing MULTICHAIN_NODE_* vars"
 # If .env exists but lacks node vars (e.g. from old predeploy hook), append them
 if ! grep -q "MULTICHAIN_NODE_ADMIN_IP" "$ENV_FILE"; then
 echo "POSTDEPLOY: Appending missing MULTICHAIN_NODE_* vars to existing .env"
 {
 echo ""
 echo "# MultiChain node registry (appended by postdeploy hook)"
 echo "MULTICHAIN_NODE_ADMIN_IP=${MULTICHAIN_NODE_ADMIN_IP:-127.0.0.1}"
 echo "MULTICHAIN_NODE_ADMIN_PRIVATE_IP=${MULTICHAIN_NODE_ADMIN_PRIVATE_IP:-127.0.0.1}"
 echo "MULTICHAIN_NODE_ADMIN_RPC_PORT=${MULTICHAIN_NODE_ADMIN_RPC_PORT:-6834}"
 echo "MULTICHAIN_NODE_ADMIN_P2P_PORT=${MULTICHAIN_NODE_ADMIN_P2P_PORT:-6835}"
 echo "MULTICHAIN_NODE_ADMIN_NAME=${MULTICHAIN_NODE_ADMIN_NAME:-Primary Node}"
 echo "MULTICHAIN_NODE_ADMIN_ROLE=${MULTICHAIN_NODE_ADMIN_ROLE:-Administrator}"
 echo ""
 echo "MULTICHAIN_NODE_BAC_SECRETARIAT_IP=${MULTICHAIN_NODE_BAC_SECRETARIAT_IP:-127.0.0.1}"
 echo "MULTICHAIN_NODE_BAC_SECRETARIAT_PRIVATE_IP=${MULTICHAIN_NODE_BAC_SECRETARIAT_PRIVATE_IP:-127.0.0.1}"
 echo "MULTICHAIN_NODE_BAC_SECRETARIAT_RPC_PORT=${MULTICHAIN_NODE_BAC_SECRETARIAT_RPC_PORT:-6834}"
 echo "MULTICHAIN_NODE_BAC_SECRETARIAT_P2P_PORT=${MULTICHAIN_NODE_BAC_SECRETARIAT_P2P_PORT:-6835}"
 echo "MULTICHAIN_NODE_BAC_SECRETARIAT_NAME=${MULTICHAIN_NODE_BAC_SECRETARIAT_NAME:-BAC Secretariat}"
 echo "MULTICHAIN_NODE_BAC_SECRETARIAT_ROLE=${MULTICHAIN_NODE_BAC_SECRETARIAT_ROLE:-Secretariat}"
 echo ""
 echo "MULTICHAIN_NODE_BAC_CHAIRMAN_IP=${MULTICHAIN_NODE_BAC_CHAIRMAN_IP:-127.0.0.1}"
 echo "MULTICHAIN_NODE_BAC_CHAIRMAN_PRIVATE_IP=${MULTICHAIN_NODE_BAC_CHAIRMAN_PRIVATE_IP:-127.0.0.1}"
 echo "MULTICHAIN_NODE_BAC_CHAIRMAN_RPC_PORT=${MULTICHAIN_NODE_BAC_CHAIRMAN_RPC_PORT:-6834}"
 echo "MULTICHAIN_NODE_BAC_CHAIRMAN_P2P_PORT=${MULTICHAIN_NODE_BAC_CHAIRMAN_P2P_PORT:-6835}"
 echo "MULTICHAIN_NODE_BAC_CHAIRMAN_NAME=${MULTICHAIN_NODE_BAC_CHAIRMAN_NAME:-BAC Chairman}"
 echo "MULTICHAIN_NODE_BAC_CHAIRMAN_ROLE=${MULTICHAIN_NODE_BAC_CHAIRMAN_ROLE:-Chairman}"
 echo ""
 echo "MULTICHAIN_NODE_HOPE_IP=${MULTICHAIN_NODE_HOPE_IP:-127.0.0.1}"
 echo "MULTICHAIN_NODE_HOPE_PRIVATE_IP=${MULTICHAIN_NODE_HOPE_PRIVATE_IP:-127.0.0.1}"
 echo "MULTICHAIN_NODE_HOPE_RPC_PORT=${MULTICHAIN_NODE_HOPE_RPC_PORT:-6834}"
 echo "MULTICHAIN_NODE_HOPE_P2P_PORT=${MULTICHAIN_NODE_HOPE_P2P_PORT:-6835}"
 echo "MULTICHAIN_NODE_HOPE_NAME=${MULTICHAIN_NODE_HOPE_NAME:-HOPE}"
 echo "MULTICHAIN_NODE_HOPE_ROLE=${MULTICHAIN_NODE_HOPE_ROLE:-HOPE}"
 } >> "$ENV_FILE"
 echo "POSTDEPLOY: MULTICHAIN_NODE_* vars appended successfully"
 else
 echo "POSTDEPLOY: .env already contains MULTICHAIN_NODE_* vars — skipping"
 fi
fi

# Always recache config to pick up new env vars
cd "$APP_DIR" && php artisan config:cache 2>/dev/null && echo "POSTDEPLOY: Config cached successfully"
